import { DocumentService } from '../core.service';
import { AIOrchestratorService } from './ai-orchestrator.service';
import { ITranscriptionResult } from './ai-types';

/**
 * AIIntegrationService connects the AI outputs back to the core Document system.
 * It fulfills the "Document Insertion" requirement in Document 3.
 */
export class AIIntegrationService {
  constructor(
    private docService: DocumentService,
    private aiOrchestrator: AIOrchestratorService
  ) {}

  /**
   * Converts an AI-generated summary into a structured Markdown block 
   * and inserts it into the specified document.
   * 
   * @param docId The ID of the document to update
   * @param summaryText The text generated by the LLM
   */
  async insertSummaryBlock(docId: string, summaryText: string): Promise<void> {
    console.log(`[AIIntegrationService] Inserting summary block into document: ${docId}`);

    const newBlockId = `summary_${Date.now()}`;

    // Document에서 직접 블록을 추가하고 저장
    const doc = await this.docService.getDocumentById(docId);
    if (!doc) {
      throw new Error(`문서를 찾을 수 없습니다: ${docId}`);
    }

    doc.blocks.push({
      id: newBlockId,
      type: 'text', // Using existing text plugin capability
      updatedAt: new Date(),
      data: {
        content: summaryText,
        format: 'markdown',
        isAiGenerated: true
      }
    });

    await this.docService.updateDocument(docId, { blocks: doc.blocks });
    
    console.log(`[AIIntegrationService] Summary block successfully inserted.`);
  }

  /**
   * Orchestrates the full flow: From raw transcripts to a new summary block.
   */
  async processFullMeetingToSummary(docId: string, transcripts: ITranscriptionResult[]): Promise<void> {
    const summary = await this.aiOrchestrator.generateMeetingSummary(transcripts);
    await this.insertSummaryBlock(docId, summary);
  }
}
